site_name: eCactus ECOS API Client
theme:
  name: material
  features:
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        options:
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_bases: false
          members_order: source
          show_symbol_type_heading: true
          docstring_section_style: table
          filters: ["!^_", "^__init__$"]
- search
nav:
  - Home: index.md
  - api.md
repo_url: https://github.com/gmasse/ecactus-ecos
watch:
  - src