name: Lint and Test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main
      - dev
      - gh-pages
  pull_request:
    paths-ignore:
    # Skip running tests if changes are only in documentation directories
    - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'
      - name: Lint with ruff
        run: ruff check
      - name: Typing checks with mypy
        run: mypy
      - name: Test with pytest
        run: pytest

  full_tests:
    needs: test
    # Only run when there is activity on a pull request or when manually triggered
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          # Already run in previous test job
          - os: ubuntu-latest
            python-version: '3.11'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'
      - name: Test with pytest
        run: pytest
